apiVersion: skaffold/v2alpha2
kind: Config
metadata:
  name: metrodb
build:
  artifacts:
  - image: nicokahlert/metrodb
    context: container/alpine
    #kaniko:
    #  dockerfile: container/alpine/Dockerfile
    #  buildArgs: 
    #    cache: --no-cache
    #cluster:
    #  pullSecretName: kaniko-build-secret
    #  namespace: metrodb
deploy:
  kubectl:
    manifests:
    - deployment/kubernetes/*.yaml
