version: '3'
services:
  logd1:
    image: nicokahlert/metrodb
    environment: 
      LOGD_DB_PATH: /var/metrodb/logd
    command: '/bin/logd'
    volumes: 
      - logd1:/var/metrodb/logd
  logd2:
    image: nicokahlert/metrodb
    environment: 
      LOGD_DB_PATH: /var/metrodb/logd
    command: '/bin/logd'
    volumes: 
      - logd2:/var/metrodb/logd
  logd3:
    image: nicokahlert/metrodb
    environment: 
      LOGD_DB_PATH: /var/metrodb/logd
    command: '/bin/logd'
    volumes: 
      - logd3:/var/metrodb/logd
  mapd1:
    image: nicokahlert/metrodb
    ports: 
    - "7550:7550"
    environment: 
      MAPD_INDEX_PATH: /var/metrodb/mapd
    command: '/bin/mapd logd1 logd2 logd3'
    volumes: 
      - mapd1:/var/metrodb/mapd
    depends_on: 
      - logd1
      - logd2
      - logd3
  mapd2:
    image: nicokahlert/metrodb
    #ports: 
    #- "7550:7550"
    environment: 
      MAPD_INDEX_PATH: /var/metrodb/mapd
    command: '/bin/mapd logd1 logd2 logd3'
    volumes: 
      - mapd2:/var/metrodb/mapd
    depends_on: 
      - logd1
      - logd2
      - logd3
  mapd3:
    image: nicokahlert/metrodb
    #ports: 
    #- "7550:7550"
    environment: 
      MAPD_INDEX_PATH: /var/metrodb/mapd
    command: '/bin/mapd logd1 logd2 logd3'
    volumes: 
      - mapd3:/var/metrodb/mapd
    depends_on: 
      - logd1
      - logd2
      - logd3
  mond:
    image: nicokahlert/metrodb
    command: '/bin/mond'
    depends_on: 
      - mapd1
      - mapd2
      - mapd3
  toolbox:
    image: nicokahlert/metrodb
    ports:
    - "7080:7080"
    command: '/bin/mapd-util mapd1 serve 7080'
    depends_on: 
      - mapd1
      - mapd2
      - mapd3
volumes: 
  mapd1:
  mapd2:
  mapd3:
  logd1:
  logd2:
  logd3:


