apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logds
  namespace: metrodb
spec:
  selector:
    matchLabels:
      app: logd
  serviceName: logds
  replicas: 3
  template:
    metadata:
      labels:
        app: logd
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: logd 
        image: nicokahlert/metrodb@sha256:322c3f033ee14248ab21a3eeb387dcfb521a3512d360afcf62fae8048e629e5b
        env:
        - name: LOGD_DB_PATH
          value: /var/metrodb/logd
        command:
          - /bin/logd
        ports:
        - containerPort: 7558
          name: logd-grpc
        resources:
          limits:
            memory: "128Gi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "50m"
        volumeMounts:
        - name: persistent-log
          mountPath: /var/metrodb/logd
  volumeClaimTemplates:
  - metadata:
      name: persistent-log
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi