apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mapds
  namespace: metrodb
spec:
  selector:
    matchLabels:
      app: mapd
  serviceName: mapds
  replicas: 3
  template:
    metadata:
      labels:
        app: mapd
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: mapd 
        image: nicokahlert/metrodb
        env:
        - name: MAPD_INDEX_PATH
          value: /var/metrodb/mapd
        command:
          - /bin/mapd
        args: 
          - -cluster 
          - mapd-0.mapds.metrodb.svc.cluster.local,mapd-1.mapds.metrodb.svc.cluster.local,mapd-2.mapds.metrodb.svc.cluster.local
          - -logds
          - logd-0.logds.metrodb.svc.cluster.local,logd-1.logds.metrodb.svc.cluster.local,logd-2.logds.metrodb.svc.cluster.local
        ports:
        - containerPort: 7558
          name: mapd-grpc
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "50m"
        volumeMounts:
        - name: persistent-index
          mountPath: /var/metrodb/logd
  volumeClaimTemplates:
  - metadata:
      name: persistent-index
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi