apiVersion: apps/v1
kind: Deployment
metadata:
  name: mond
  namespace: metrodb
spec:
  selector:
    matchLabels:
      app: mond
  template:
    metadata:
      labels:
        app: mond
    spec:
      containers:
      - name: mond
        image: nicokahlert/metrodb@sha256:322c3f033ee14248ab21a3eeb387dcfb521a3512d360afcf62fae8048e629e5b
        command:
          - /bin/mond
        args:
          - mapd-0.mapd
          - mapd-1.mapd
          - mapd-2.mapd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
