apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: metrodb
  labels:
    name: toolbox
spec:
  containers:
  - name: toolbox
    image: nicokahlert/metrodb
    command:
      - /bin/mapd-util
    args:
      - metrodb
      - serve
      - '7080'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: api
        hostPort: 7080
        containerPort: 7080
        protocol: "TCP"