apiVersion: apps/v1
kind: Deployment
metadata:
  name: mond
spec:
  selector:
    matchLabels:
      app: mond
  template:
    metadata:
      labels:
        app: mond
    spec:
      containers:
      - name: mond
        image: nicokahlert/metrodb
        command: ["/bin/mond"]
        args: ["mapd-metrodb-0.cluster.local","metrodb-mapd-1.cluster.local","metrodb-mapd-2.cluster.local"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
