apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  labels:
    name: toolbox
spec:
  containers:
  - name: toolbox
    image: nicokahlert/metrodb
    command:
      - "/bin/mapd-util"
      - "metrodb-mapd-1.cluster.local serve"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: api
        hostPort: 7080
        containerPort: 7080
        protocol: "TCP"